version: '3'
services:
  flask1:
    build: ./flask
    ports:
      - "5001:5000"
  flask2:
    build: ./flask
    ports:
      - "5002:5000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask1
      - flask2
networks:
  default:
    name: flask_net
