version: '3'
services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  flask:
    image: flaskapp
    labels:
      - "traefik.http.routers.flask.rule=Host(`flask.local`)"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wp
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`wp.local`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
