version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - appnet

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

networks:
  appnet:
