version: '3'
services:
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5000:80"
  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5001:80"
  redis:
    image: redis
  worker:
    image: dockersamples/examplevotingapp_worker
  db:
    image: postgres

networks:
  default:
    name: voteapp_net
